app: qwik-lambda-app
org: jamber
service: qwik-lambda-app
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs18.x
  stage: ${opt:stage, 'prod'}
  memorySize: 512
  timeout: 10
  environment:
    SUPABASE_KEY: ${param:SUPABASE_KEY}
    NOTION_API_KEY: ${param:NOTION_API_KEY}
    NOTION_BLOG_DATABASE: ${param:NOTION_BLOG_DATABASE}

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000
  customDomain:
    domainName: ${param:DOMAIN_NAME}
    basePath: "/"
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
  - serverless-domain-manager
