app: qwik-lambda-app
org: jamber
service: qwik-lambda-app
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  stage: dev
  memorySize: 512
  timeout: 10
  environment:
    SUPABASE_KEY: ${param:SUPABASE_KEY}
    NOTION_API_KEY: ${param:NOTION_API_KEY}
    NOTION_BLOG_DATABASE: ${param:NOTION_BLOG_DATABASE}

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: false
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
