app: qwik-lambda-app
org: jamber
service: qwik-lambda-app
frameworkVersion: "3"
useDotenv: true

stages:
  default:
    region: us-west-1
    params:
      SUPABASE_KEY: ${env:SUPABASE_KEY}
      NOTION_API_KEY: ${env:NOTION_API_KEY}
      NOTION_BLOG_DATABASE: ${env:NOTION_BLOG_DATABASE}
  prod:
    region: ap-southeast-2

provider:
  name: aws
  region: ap-southeast-2
  runtime: nodejs18.x
  memorySize: 512
  timeout: 10
  environment:
    SUPABASE_KEY: ${param:SUPABASE_KEY}
    NOTION_API_KEY: ${param:NOTION_API_KEY}
    NOTION_BLOG_DATABASE: ${param:NOTION_BLOG_DATABASE}

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: true
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
