app: qwik-lambda-app
org: jamber
service: qwik-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  memorySize: 128
  timeout: 10
  stage: dev
  environment:
    SUPABASE_KEY: dev

functions:
  qwik:
    handler: server/entry_aws-lambda.qwikApp
    events:
      - httpApi: "*"

custom:
  serverless-offline:
    httpPort: 4000

package:
  excludeDevDependencies: false
  patterns:
    - "!*"
    - "!*/**"
    - "server/**"
    - "dist/**"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
