/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "NotionApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SupabaseKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "showcaseApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "showcaseBlogPosts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "showcaseRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}